###

GET http://localhost:3000/books/
Authorization: Bearer JWT_TOKEN

###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"ravi",
    "username":"ravi",
    "password": "ravi@2021",
    "gender": "Male",
    "location":"parvathipuram"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"ravi",
    "password": "ravi@2021"
}